import type { Metadata } from "next";
import "@/styles/globals.css";
import { Poppins } from "next/font/google";

const mainFontFamily = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Artêmia Móveis Planejados",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={mainFontFamily.className}>
      <body>{children}</body>
    </html>
  );
}
